global:
  scrape_interval:     15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['172.16.100.5:10100']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['172.16.100.5:10101', '*.mistysnowrealms.net:10101']

  - job_name: 'pve'
    static_configs:
      - targets:
        - 172.16.99.1  # Proxmox VE node 1
    metrics_path: /pve
    params:
      module: [default]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 172.16.100.5:10101
