- name: Install Docker Engine
  hosts: docker
  become: yes
 
  tasks:
    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg2
          - software-properties-common
 
    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present
 
    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/debian bookworm stable
        state: present
 
    - name: Install Docker Engine
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
 
    - name: Add user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
 
    - name: Start Docker service
      service:
        name: docker
        state: started

- name: Dockge setup
  hosts: docker
  become: yes

  tasks: 
    - name: Create Dockge directory
      file:
        path: /opt/dockge
        state: directory
        mode: '0755'

    - name: Create Stacks directory
      file:
        path: /opt/stacks
        state: directory
        mode: '0755'

    - name: Download Dockge docker compose yml file
      get_url:
        url: https://raw.githubusercontent.com/louislam/dockge/master/compose.yaml 
        validate_certs: false
        dest: "/opt/dockge/compose.yaml"
        mode: '0755'

    - name: Create and start service
      community.docker.docker_compose_v2:
        project_src: /opt/dockge/
      register: output

    - name: Show results
      ansible.builtin.debug:
        var: output
