- name: Install apt
  hosts: "*"
  tasks:
    - name: apt
      apt:
        update_cache: yes
        upgrade: 'yes'
      become: yes
        
- name: Install latest qemu-guest-agent
  hosts: "*"
  tasks:
    - name: Install qemu-guest-agent
      apt:
        name: qemu-guest-agent
        state: present
        update_cache: true
      become: true

- name: Install latest curl
  hosts: "*"
  tasks:
    - name: Install curl
      apt:
        name: curl
        state: present
        update_cache: true
      become: true

- name: Install latest neofetch
  hosts: "*"
  tasks:
    - name: Install neofetch
      apt:
        name: neofetch
        state: present
        update_cache: true
      become: true

- name: Copy the MOTD
  hosts: "*"
  - name: Remove MOTD and Copy MOTD script to server
  tasks:
    ansible.builtin.file:
      path: /etc/motd
      state: absent
    copy: 
      src=../templates/motd.sh
      dest=/etc/profile.d/motd.sh
  become: true