image:
  name: gitlab.msrls.local:5000/root/container-debian-12
  entrypoint: [""]

stages:
   - deploy

deploy:
   stage: deploy
   script:
      - mkdir -p ~/.ssh
      - cat ${gitlab_key} > ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa
      - ssh -o StrictHostKeyChecking=no monitor.msrls.local "docker ps -a"
      - ssh -o StrictHostKeyChecking=no monitor.msrls.local "docker kill uptime-kuma"
      - scp -o StrictHostKeyChecking=no uptime-kuma/docker-compose.yaml monitor.msrls.local:/opt/stacks/uptime-kuma
      - ssh -o StrictHostKeyChecking=no monitor.msrls.local "ls -alhrt /opt/stacks/uptime-kuma"
      - ssh -o StrictHostKeyChecking=no monitor.msrls.local "cd /opt/stacks/uptime-kuma/ && docker compose up -d"