---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Hypervisors:
    - Atlas01A Node:
        icon: proxmox
        description: Atlas01A PVE Node
        siteMonitor: https://atlas01a.sys.msrls.net/
        widget:
           type: proxmox
           url: https://atlas01a.msrls.local:8006
           username: "{{HOMEPAGE_VAR_PROXMOX_USER}}"
           password: "{{HOMEPAGE_VAR_PROXMOX_API_KEY}}"
           node: atlas01a
    - Anibis01A Node:
        icon: proxmox
        description: Anubis01A PVE Node
        siteMonitor: https://anubis01a.sys.msrls.net/
        widget:
           type: proxmox
           url: https://anubis01a.msrls.local:8006
           username: "{{HOMEPAGE_VAR_PROXMOX_USER}}"
           password: "{{HOMEPAGE_VAR_PROXMOX_API_KEY}}"
           node: anubis01a

- Storage:
    - Gaia01A NAS:
        icon: truenas-scale
        description: Gaia01A TrueNAS
        siteMonitor: https://gaia01a.sys.msrls.net/
        widget:
           type: truenas
           url: https://gaia01a.msrls.local:4443
           key: "{{HOMEPAGE_VAR_TRUENAS_API_KEY}}" # not required if using username / password
           enablePools: true # optional, defaults to false
           nasType: scale # defaults to scale, must be set to 'core' if using enablePools with TrueNAS Core

- Systems:
   - Pi-Hole DNS:
        icon: pi-hole
        description: Pi-Hole Upstream DNS Server
        siteMonitor: https://dns-us.sys.msrls.net/admin/
        widget:
           type: pihole
           url: http://dns-us.msrls.local
           key: "{{HOMEPAGE_VAR_PIHOLE_API_KEY}}"
   - Internal Reverse Proxy:
        icon: nginx-proxy-manager
        description: Internal Nginx Reverse Proxy
        siteMonitor: https://in-proxy.sys.msrls.net/
        widget:
           type: npm
           url: http://in-proxy.msrls.local:81
           username: "{{HOMEPAGE_VAR_DEV_NPM_USER}}"
           password: "{{HOMEPAGE_VAR_DEV_NPM_PW}}"

- Apps:
   - JellyFin:
        href: https://jellyfin.app.msrls.net/
        icon: jellyfin
        description: JellyFin
        siteMonitor: https://jellyfin.app.msrls.net/
        widget:
           type: jellyfin
           url: https://jellyfin.app.msrls.net
           key: "{{HOMEPAGE_VAR_JELLY_API_KEY}}"
           enableBlocks: true # optional, defaults to false
           enableNowPlaying: true # optional, defaults to true
           enableUser: true # optional, defaults to false
           showEpisodeNumber: true # optional, defaults to false
           expandOneStreamToTwoRows: false # optional, defaults to true
   - EmulatorJS:
        href: https://emu-play.app.msrls.net
        icon: emulatorjs
        description: EmulatorJS - Web Retro Arcade Console 
        siteMonitor: https://emu-play.app.msrls.net
   - Pterodactyl Panel:
        href: https://ptero.app.msrls.net/
        icon: pterodactyl
        description: Game Server Manager
        siteMonitor: https://ptero.app.msrls.net/
        widget:
           type: pterodactyl
           url: https://ptero.app.msrls.net
           key: "{{HOMEPAGE_VAR_PTERO_API_KEY}}"